In [3]:
import pandas as pd
import numpy as np

# creating pandas series with default index
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums)
print(s)

# cerating pandas with custom index
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums, index=[1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:
fruits = ['Orange', 'Banana', 'Mango']
fruits = pd.Series(fruits, index=[1, 2, 3])
print(fruits)

1.0    Orange
2.0    Banana
3.0     Mango
dtype: object

In [10]:
# creating pandas series from a dictionary

dct = {'name': 'Evineldy',
       'country': 'Mozambique',
       'city': 'Maputo'}

dct = pd.Series(dct)
print(dct)

name         Evineldy
country    Mozambique
city           Maputo
dtype: object

In [15]:
# creating a constant pandas series

s = pd.Series(10, index=[1, 2, 3])
print(s)

1    10
2    10
3    10
dtype: int64

In [16]:
s = pd.Series(np.linspace(5, 20, 10))
print(s)

0     5.000000
1     6.666667
2     8.333333
3    10.000000
4    11.666667
5    13.333333
6    15.000000
7    16.666667
8    18.333333
9    20.000000
dtype: float64

In [20]:
# Creating dataframes from list of lists
data = [
    ['Evineldy', 'Mozambique', 'Maputo'],
    ['Kelsy', 'Mozambique', 'Maputo'],
    ['Judy', 'Mozambique', 'Maputo']
    ]

df = pd.DataFrame(data, columns=['Names', 'Country', 'City'], index=[1,2,3])
print(df)

      Names     Country    City
1  Evineldy  Mozambique  Maputo
2     Kelsy  Mozambique  Maputo
3      Judy  Mozambique  Maputo

In [22]:
# Creating dataframe using Dictionary

data = {
    'Name': ['Evineldy', 'Judy', 'Kelsy'],
    'Country': ['Mozambique', 'Sweden', 'Portugal'],
    'City': ['Maputo', 'Stockholm', 'Lisboa'],
}

df = pd.DataFrame(data, index=[1,2,3])
print(df)

       Name     Country       City
1  Evineldy  Mozambique     Maputo
2      Judy      Sweden  Stockholm
3     Kelsy    Portugal     Lisboa

In [23]:
data = [
    {'Name': 'Evineldy', 'Country':'Mozambique', 'City': 'Maputo'},
    {'Name': 'Judy', 'Country':'Sweden', 'City': 'Stockholm'},
    {'Name': 'Kelsy', 'Country':'Portugal', 'City': 'Lisbon'}
]

df = pd.DataFrame(data, index=[1,2,3])
print(df)

       Name     Country       City
1  Evineldy  Mozambique     Maputo
2      Judy      Sweden  Stockholm
3     Kelsy    Portugal     Lisbon

In [28]:
# reading CSV file using pandas
import pandas as pd

df = pd.read_csv('weight-height.csv')
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [ ]:
# filtering the first 5 rows
print(df.head())

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [33]:
# filtering the last 5 rows
print(df.tail())

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [35]:
# number of rows
print(df.shape)

(10000, 3)

In [36]:
# getting all the columns

print(df.columns)

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [43]:
# specific column using the column key
heights = df['Height']
weights = df['Weight']
print('Heights: ')
print(heights)
print('Weights: ')
print(weights)

Heights:
0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64
Weights:
0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...
9995    136.777454
9996    170.867906
9997    128.475319
9998    163.852461
9999    113.649103
Name: Weight, Length: 10000, dtype: float64

In [ ]:
print(len(heights) == len(weights))

False

In [46]:
print(heights.describe())

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: Height, dtype: float64

In [47]:
print(df.describe())

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [3]:
import pandas as pd
nums = [1, 2, 3, 4, 5]
s = pd.Series(nums, index=[1,2,3,4,5])
print(s)

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [13]:
data = [
    ['Asabeneh', 'Finland', 'Helsinki'],
    ['david'],
    []
]
df = pd.DataFrame(data, columns=['Name', 'Country', 'City'])

print(df)

       Name  Country      City
0  Asabeneh  Finland  Helsinki
1     david     None      None
2      None     None      None

In [16]:
data = {'Name': ['Asabeneh', 'David', 'John'] ,
        'Country': ['Finland', 'UK', 'Sweden'],
        'City': ['Helsinki', 'London', 'Stockholm']}
df = pd.DataFrame(data)
df

       Name  Country       City
0  Asabeneh  Finland   Helsinki
1     David       UK     London
2      John   Sweden  Stockholm

In [17]:
data = [
    {'Name': 'Tom', 'Country': 'Finland', 'City': 'Helsinki'},
    {'Name': 'David', 'Country': 'UK', 'City': 'London'},
    {'Name': 'John', 'Country': 'Sweden', 'City': 'Stockholm'}
]

df = pd.DataFrame(data)
df

    Name  Country       City
0    Tom  Finland   Helsinki
1  David       UK     London
2   John   Sweden  Stockholm

In [18]:
df = pd.read_csv('weight-height.csv')
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [22]:
# Reading the first 5 rows
print('First five rows below: ')
df.head()

First five rows below:

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [23]:
# Reading the last 5 rows
print('Last five rows below: ')
df.tail()

Last five rows below:

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [25]:
# Descriptive statistics
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [26]:
# Looking for the file size
df.shape

(10000, 3)

In [27]:
# Getting all the columns
df.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [29]:
# Getting a specific column using the column key
heights = df['Height']
heights

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [30]:
heights.describe()

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: Height, dtype: float64

In [31]:
# Creating a DataFrame

import numpy as np
data = [
    {'Name': 'Tom', 'Country': 'Finland', 'City': 'Helsinki'},
    {'Name': 'David', 'Country': 'UK', 'City': 'London'},
    {'Name': 'John', 'Country':'Sweden', 'City':'Stockholm'}
]
df = pd.DataFrame(data)
df

    Name  Country       City
0    Tom  Finland   Helsinki
1  David       UK     London
2   John   Sweden  Stockholm

In [32]:
# Adding a new column

weights = [74, 78, 69]
df['Weight'] = weights
df

    Name  Country       City  Weight
0    Tom  Finland   Helsinki      74
1  David       UK     London      78
2   John   Sweden  Stockholm      69

In [52]:
# Adding another column
heights = [173, 175, 169]
df['Height'] = heights
df

    Name  Country       City  Weight  Height   BMI
0    Tom  Finland   Helsinki      74     173  74.0
1  David       UK     London      78     175  78.0
2   John   Sweden  Stockholm      69     169  69.0

In [54]:
df['Height'] = df['Height'] * 0.01
df

    Name  Country       City  Weight  Height   BMI
0    Tom  Finland   Helsinki      74    1.73  74.0
1  David       UK     London      78    1.75  78.0
2   John   Sweden  Stockholm      69    1.69  69.0

In [56]:
df['BMI'] = df['Weight'] / df['Height'] ** 2
df

    Name  Country       City  Weight  Height        BMI
0    Tom  Finland   Helsinki      74    1.73  24.725183
1  David       UK     London      78    1.75  25.469388
2   John   Sweden  Stockholm      69    1.69  24.158818

In [57]:
def calculate_bmi ():
    weights = df['Weight']
    heights = df['Height']
    bmi = []
    for w,h in zip(weights, heights):
        b = w/(h**2)
        bmi.append(b)
    return bmi

bmi = calculate_bmi()

df['BMI'] = bmi
df

    Name  Country       City  Weight  Height        BMI
0    Tom  Finland   Helsinki      74    1.73  24.725183
1  David       UK     London      78    1.75  25.469388
2   John   Sweden  Stockholm      69    1.69  24.158818